/**********************************************************************  Filename:  catch.cpp  Chapter:   9      Exceptions  Compiler:  Borland C++     Version 5.01      Summer 1998  C++ for C Programmers, Edition 3     By Ira Pohl********************************************************************/#include <iostream>#include <stdlib>//using namespace std;void foo(){   int  i, j;   i = 14;   j = 15;//   throw i;}void call_foo(){   int  k;   k  = 12;   foo();//   throw ("This is from call_foo");}void call_foo2(){   double  x = 1.3;   throw (x);}int main(){   try {      call_foo();  //foo exitted with i and j destroyed      call_foo2();   }   catch(char* message)   {      cerr << message << endl;      exit(1);   }   catch(int n) { cout << "\ncaught it " << n << endl; }   catch( ... )      //default action to be taken   {      cerr << "THAT'S ALL FOLKS." << endl;      abort();   }   int look; cin >> look;}